version: '2'

services:
  bankass:
    image: absimas/bank
    ports:
      - 5002:4321
  bankasr:
    image: ricardaskazakevicius/superbank:v11
    ports:
      - 80:80
    depends_on:
      - bankass
