version: '2'

services:
  bankr:
    image: "ricardaskazakevicius/superbank:v11"
    ports:
      - 80:1234
  banks:
    image: "absimas/bank:latest"
    ports:
      - 5000:5000
    depends_on:
      - bankr
