version: '2'

services:
  bankr:
    image: "ricardaskazakevicius/superbank:v11"
    ports:
      - 80:1234
  banks:
    image: "absimas/bank:latest"
    ports:
      - 50:80
    depends_on:
      - bankr
