version: '2'

services:
  controller:
    image: "ricardaskazakevicius/controller:v1"
    ports:
     - 80:888
  bankr:
    image: "ricardaskazakevicius/superbank:v11"
    ports:
      - 444:1234
  banks:
    image: "absimas/bank:latest"
    ports:
      - 50:80
    depends_on:
      - bankr
